[package]
name = "jsonrpsee-types"
version = "0.2.0-alpha.4"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Shared types for jsonrpsee"
edition = "2018"
license = "MIT"

[dependencies]
async-trait = "0.1"
beef = "0.5"
futures = { default-features = false, features = ["std"], version = "0.3" }
log = { default-features = false, version = "0.4" }
serde = { default-features = false, features = ["derive"], version = "1.0" }
serde_json = { default-features = false, features = ["alloc", "raw_value", "std"], version = "1.0" }
smallvec = "1.0"
thiserror = "1.0"
